<?php

namespace Database\Seeders;

use App\Models\DefaultKeyword;
use Illuminate\Database\Seeder;
use App\Models\Screen;

class ScreenkeywordSeeder extends Seeder
{

  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {
	$screen_data =
	[
		[
			'screenID' => '1',
			'ScreenName' => 'WalkThroughScreen',
			'keyword_data' => [
				[
					'screenId' => '1',
					'keyword_id' => 1,
					'keyword_name' => 'lblWalkTitle1',
					'keyword_value' => 'Find The Right Workout \nfor What You Need',
				],
				[
					'screenId' => '1',
					'keyword_id' => 2,
					'keyword_name' => 'lblWalkTitle2',
					'keyword_value' => 'Choose Proper Workout \n& Diet Plan to Stay Fit.',
				],
				[
					'screenId' => '1',
					'keyword_id' => 3,
					'keyword_name' => 'lblWalkTitle3',
					'keyword_value' => 'Easily Track Your Daily Activity',
				],
				[
					'screenId' => '1',
					'keyword_id' => 4,
					'keyword_name' => 'lblGetStarted',
					'keyword_value' => 'Get Started',
				],
				[
					'screenId' => '1',
					'keyword_id' => 5,
					'keyword_name' => 'lblNext',
					'keyword_value' => 'Next',
				],
				[
					'screenId' => '1',
					'keyword_id' => 6,
					'keyword_name' => 'lblSkip',
					'keyword_value' => 'Skip',
				],
				[
					'screenId' => '1',
					'keyword_id' => 231,
					'keyword_name' => 'lblEmailIsInvalid',
					'keyword_value' => 'Email is invalid',
				],
			],
		],
		[
			'screenID' => '2',
			'ScreenName' => 'SignInScreen',
			'keyword_data' => [
				[
					'screenId' => '2',
					'keyword_id' => 7,
					'keyword_name' => 'lblLogin',
					'keyword_value' => 'Login',
				],
				[
					'screenId' => '2',
					'keyword_id' => 8,
					'keyword_name' => 'lblWelcomeBack',
					'keyword_value' => 'Welcome Back,',
				],
				[
					'screenId' => '2',
					'keyword_id' => 9,
					'keyword_name' => 'lblWelcomeBackDesc',
					'keyword_value' => 'Hello there, sign in to continue!',
				],
				[
					'screenId' => '2',
					'keyword_id' => 10,
					'keyword_name' => 'lblEmail',
					'keyword_value' => 'Email',
				],
				[
					'screenId' => '2',
					'keyword_id' => 11,
					'keyword_name' => 'lblEnterEmail',
					'keyword_value' => 'Enter Email',
				],
				[
					'screenId' => '2',
					'keyword_id' => 12,
					'keyword_name' => 'lblPassword',
					'keyword_value' => 'Password',
				],
				[
					'screenId' => '2',
					'keyword_id' => 13,
					'keyword_name' => 'lblEnterPassword',
					'keyword_value' => 'Enter Password',
				],
				[
					'screenId' => '2',
					'keyword_id' => 14,
					'keyword_name' => 'lblRememberMe',
					'keyword_value' => 'Remember Me',
				],
				[
					'screenId' => '2',
					'keyword_id' => 15,
					'keyword_name' => 'lblForgotPassword',
					'keyword_value' => 'Forgot Password?',
				],
				[
					'screenId' => '2',
					'keyword_id' => 16,
					'keyword_name' => 'lblOr',
					'keyword_value' => 'Or',
				],
				[
					'screenId' => '2',
					'keyword_id' => 17,
					'keyword_name' => 'lblNewUser',
					'keyword_value' => 'New User?',
				],
				[
					'screenId' => '2',
					'keyword_id' => 18,
					'keyword_name' => 'lblRegisterNow',
					'keyword_value' => 'Register Now',
				],
				[
					'screenId' => '2',
					'keyword_id' => 19,
					'keyword_name' => 'lblContactAdmin',
					'keyword_value' => 'Contact to administrator',
				],
			],
		],
		[
			'screenID' => '3',
			'ScreenName' => 'SignUpStep1Component',
			'keyword_data' => [
				[
					'screenId' => '3',
					'keyword_id' => 20,
					'keyword_name' => 'lblTellUsAboutYourself',
					'keyword_value' => 'Tell us about yourself!',
				],
				[
					'screenId' => '3',
					'keyword_id' => 21,
					'keyword_name' => 'lblFirstName',
					'keyword_value' => 'First Name',
				],
				[
					'screenId' => '3',
					'keyword_id' => 22,
					'keyword_name' => 'lblEnterFirstName',
					'keyword_value' => 'Enter First Name',
				],
				[
					'screenId' => '3',
					'keyword_id' => 23,
					'keyword_name' => 'lblLastName',
					'keyword_value' => 'Last Name',
				],
				[
					'screenId' => '3',
					'keyword_id' => 24,
					'keyword_name' => 'lblEnterLastName',
					'keyword_value' => 'Enter Last Name',
				],
				[
					'screenId' => '3',
					'keyword_id' => 25,
					'keyword_name' => 'lblPhoneNumber',
					'keyword_value' => 'Phone Number',
				],
				[
					'screenId' => '3',
					'keyword_id' => 26,
					'keyword_name' => 'lblEnterPhoneNumber',
					'keyword_value' => 'Enter Phone Number',
				],
				[
					'screenId' => '3',
					'keyword_id' => 27,
					'keyword_name' => 'lblConfirmPassword',
					'keyword_value' => 'Confirm Password',
				],
				[
					'screenId' => '3',
					'keyword_id' => 28,
					'keyword_name' => 'lblEnterConfirmPwd',
					'keyword_value' => 'Enter Confirm Password',
				],
				[
					'screenId' => '3',
					'keyword_id' => 29,
					'keyword_name' => 'errorPwdLength',
					'keyword_value' => 'Password length should be more than 6',
				],
				[
					'screenId' => '3',
					'keyword_id' => 30,
					'keyword_name' => 'errorPwdMatch',
					'keyword_value' => 'Both password should be matched',
				],
				[
					'screenId' => '3',
					'keyword_id' => 31,
					'keyword_name' => 'lblAlreadyAccount',
					'keyword_value' => 'Already have an account?',
				],
			],
		],
		[
			'screenID' => '4',
			'ScreenName' => 'SignUpStep2Component',
			'keyword_data' => [
				[
					'screenId' => '4',
					'keyword_id' => 32,
					'keyword_name' => 'lblWhtGender',
					'keyword_value' => 'What\'s Your Gender?',
				],
				[
					'screenId' => '4',
					'keyword_id' => 33,
					'keyword_name' => 'lblMale',
					'keyword_value' => 'Male',
				],
				[
					'screenId' => '4',
					'keyword_id' => 34,
					'keyword_name' => 'lblFemale',
					'keyword_value' => 'Female',
				],
			],
		],
		[
			'screenID' => '5',
			'ScreenName' => 'SignUpStep3Component',
			'keyword_data' => [
				[
					'screenId' => '5',
					'keyword_id' => 35,
					'keyword_name' => 'lblHowOld',
					'keyword_value' => 'How old are you?',
				],
			],
		],
		[
			'screenID' => '6',
			'ScreenName' => 'SignUpStep4Component',
			'keyword_data' => [
				[
					'screenId' => '6',
					'keyword_id' => 36,
					'keyword_name' => 'lblLetUsKnowBetter',
					'keyword_value' => 'Let us know you better',
				],
				[
					'screenId' => '6',
					'keyword_id' => 37,
					'keyword_name' => 'lblWeight',
					'keyword_value' => 'Weight',
				],
				[
					'screenId' => '6',
					'keyword_id' => 38,
					'keyword_name' => 'lblEnterWeight',
					'keyword_value' => 'Enter Weight',
				],
				[
					'screenId' => '6',
					'keyword_id' => 39,
					'keyword_name' => 'lblHeight',
					'keyword_value' => 'Height',
				],
				[
					'screenId' => '6',
					'keyword_id' => 40,
					'keyword_name' => 'lblEnterHeight',
					'keyword_value' => 'Enter Height',
				],
				[
					'screenId' => '6',
					'keyword_id' => 41,
					'keyword_name' => 'lblDone',
					'keyword_value' => 'Done',
				],
				[
					'screenId' => '6',
					'keyword_id' => 42,
					'keyword_name' => 'lblLbs',
					'keyword_value' => 'LBS',
				],
				[
					'screenId' => '6',
					'keyword_id' => 43,
					'keyword_name' => 'lblKg',
					'keyword_value' => 'KG',
				],
				[
					'screenId' => '6',
					'keyword_id' => 44,
					'keyword_name' => 'lblCm',
					'keyword_value' => 'CM',
				],
				[
					'screenId' => '6',
					'keyword_id' => 45,
					'keyword_name' => 'lblFeet',
					'keyword_value' => 'FEET',
				],
			],
		],
		[
			'screenID' => '7',
			'ScreenName' => 'DashboardScreen',
			'keyword_data' => [
				[
					'screenId' => '7',
					'keyword_id' => 46,
					'keyword_name' => 'lblHome',
					'keyword_value' => 'Home',
				],
				[
					'screenId' => '7',
					'keyword_id' => 47,
					'keyword_name' => 'lblDiet',
					'keyword_value' => 'Diet',
				],
				[
					'screenId' => '7',
					'keyword_id' => 48,
					'keyword_name' => 'lblShop',
					'keyword_value' => 'Shop',
				],
				[
					'screenId' => '7',
					'keyword_id' => 232,
					'keyword_name' => 'lblReport',
					'keyword_value' => 'Metrics',
				],
				[
					'screenId' => '7',
					'keyword_id' => 49,
					'keyword_name' => 'lblProfile',
					'keyword_value' => 'Profile',
				],
				[
					'screenId' => '7',
					'keyword_id' => 50,
					'keyword_name' => 'lblTapBackAgainToLeave',
					'keyword_value' => 'Tap back again to leave',
				],
			],
		],
		[
			'screenID' => '8',
			'ScreenName' => 'HomeScreen',
			'keyword_data' => [
				[
					'screenId' => '8',
					'keyword_id' => 51,
					'keyword_name' => 'lblHey',
					'keyword_value' => 'Hey,',
				],
				[
					'screenId' => '8',
					'keyword_id' => 52,
					'keyword_name' => 'lblHomeWelMsg',
					'keyword_value' => 'Stay Healthy Always',
				],
				[
					'screenId' => '8',
					'keyword_id' => 53,
					'keyword_name' => 'lblSearch',
					'keyword_value' => 'Search',
				],
				[
					'screenId' => '8',
					'keyword_id' => 54,
					'keyword_name' => 'lblBodyPartExercise',
					'keyword_value' => 'Body Parts Exercises',
				],
				[
					'screenId' => '8',
					'keyword_id' => 55,
					'keyword_name' => 'lblEquipmentsExercise',
					'keyword_value' => 'Equipment-Based Exercises',
				],
				[
					'screenId' => '8',
					'keyword_id' => 56,
					'keyword_name' => 'lblWorkouts',
					'keyword_value' => 'Workouts',
				],
				[
					'screenId' => '8',
					'keyword_id' => 57,
					'keyword_name' => 'lblLevels',
					'keyword_value' => 'Workout Levels',
				],
				[
					'screenId' => '8',
					'keyword_id' => 202,
					'keyword_name' => 'lblTips',
					'keyword_value' => 'Tips',
				],
				[
					'screenId' => '8',
					'keyword_id' => 238,
					'keyword_name' => 'lblLevel',
					'keyword_value' => 'Level',
				],
				[
					'screenId' => '8',
					'keyword_id' => 241,
					'keyword_name' => 'lblDay',
					'keyword_value' => 'Day',
				],
				[
					'screenId' => '8',
					'keyword_id' => 246,
					'keyword_name' => 'lblUpdateNow',
					'keyword_value' => 'Update Now',
				],
				[
					'screenId' => '8',
					'keyword_id' => 247,
					'keyword_name' => 'lblUpdateAvailable',
					'keyword_value' => 'Update Available',
				],
				[
					'screenId' => '8',
					'keyword_id' => 248,
					'keyword_name' => 'lblUpdateNote',
					'keyword_value' => 'A new version is ready! Update now for the latest features and improvements.',
				],
				[
					'screenId' => '8',
					'keyword_id' => 249,
					'keyword_name' => 'lblGameOver',
					'keyword_value' => 'Game Over!',
				],
				[
					'screenId' => '8',
					'keyword_id' => 250,
					'keyword_name' => 'lblMainMenu',
					'keyword_value' => 'Main menu',
				],
				[
					'screenId' => '8',
					'keyword_id' => 251,
					'keyword_name' => 'lblBetterLuckNextTime',
					'keyword_value' => 'Better luck next time!',
				],
				[
					'screenId' => '8',
					'keyword_id' => 252,
					'keyword_name' => 'lblExit',
					'keyword_value' => 'Exit',
				],
				[
					'screenId' => '8',
					'keyword_id' => 253,
					'keyword_name' => 'lblMightyBrainWorkout',
					'keyword_value' => 'Mighty brain workout',
				],
				[
					'screenId' => '8',
					'keyword_id' => 254,
					'keyword_name' => 'lblGameTitle',
					'keyword_value' => 'Find a different color to check brain workout',
				],
				[
					'screenId' => '8',
					'keyword_id' => 255,
					'keyword_name' => 'lblStart',
					'keyword_value' => 'Start',
				],
				[
					'screenId' => '8',
					'keyword_id' => 256,
					'keyword_name' => 'lblPleaseWait',
					'keyword_value' => 'Please Wait',
				],
				[
					'screenId' => '8',
					'keyword_id' => 257,
					'keyword_name' => 'lblHoursAfterPlayAgain',
					'keyword_value' => 'hours after play again',
				],
				[
					'screenId' => '8',
					'keyword_id' => 258,
					'keyword_name' => 'lblBuildMuscle',
					'keyword_value' => 'Build muscle',
				],
				[
					'screenId' => '8',
					'keyword_id' => 259,
					'keyword_name' => 'lblKeepFit',
					'keyword_value' => 'Keep Fit',
				],
				[
					'screenId' => '8',
					'keyword_id' => 260,
					'keyword_name' => 'lblLoseWeight',
					'keyword_value' => 'Lose weight',
				],
				[
					'screenId' => '8',
					'keyword_id' => 261,
					'keyword_name' => 'lblFirstDescriptions1',
					'keyword_value' => 'Lower weight with higher reps and work on medium and small muscles',
				],
				[
					'screenId' => '8',
					'keyword_id' => 262,
					'keyword_name' => 'lblFirstDescriptions2',
					'keyword_value' => 'Start with basic muscle workout plans and keep your muscles fit and toned',
				],
				[
					'screenId' => '8',
					'keyword_id' => 263,
					'keyword_name' => 'lblFirstDescriptions3',
					'keyword_value' => 'Lower weight with higher reps and shorter rest times with cardio exercises',
				],
				[
					'screenId' => '8',
					'keyword_id' => 264,
					'keyword_name' => 'lblTotallyNewbie',
					'keyword_value' => 'Totally newbie',
				],
				[
					'screenId' => '8',
					'keyword_id' => 265,
					'keyword_name' => 'lblBeginner',
					'keyword_value' => 'beginner',
				],
				[
					'screenId' => '8',
					'keyword_id' => 266,
					'keyword_name' => 'lblIntermediate',
					'keyword_value' => 'Intermediate',
				],
				[
					'screenId' => '8',
					'keyword_id' => 267,
					'keyword_name' => 'lblAdvanced',
					'keyword_value' => 'Advanced',
				],
				[
					'screenId' => '8',
					'keyword_id' => 268,
					'keyword_name' => 'LblSecDesc1',
					'keyword_value' => 'I never workedout before',
				],
				[
					'screenId' => '8',
					'keyword_id' => 269,
					'keyword_name' => 'LblSecDesc2',
					'keyword_value' => 'I worked out before but not seriously',
				],
				[
					'screenId' => '8',
					'keyword_id' => 270,
					'keyword_name' => 'LblSecDesc3',
					'keyword_value' => 'I worked out before',
				],
				[
					'screenId' => '8',
					'keyword_id' => 271,
					'keyword_name' => 'LblSecDesc4',
					'keyword_value' => 'I have been working out for years',
				],
				[
					'screenId' => '8',
					'keyword_id' => 272,
					'keyword_name' => 'lblNoEquipment',
					'keyword_value' => 'No Equipment',
				],
				[
					'screenId' => '8',
					'keyword_id' => 273,
					'keyword_name' => 'lblDumbbells',
					'keyword_value' => 'Dumbbells',
				],
				[
					'screenId' => '8',
					'keyword_id' => 274,
					'keyword_name' => 'lblGarageGym',
					'keyword_value' => 'Garage Gym',
				],
				[
					'screenId' => '8',
					'keyword_id' => 275,
					'keyword_name' => 'lblFullGym',
					'keyword_value' => 'Full Gym',
				],
				[
					'screenId' => '8',
					'keyword_id' => 276,
					'keyword_name' => 'lblCustom',
					'keyword_value' => 'Custom',
				],
				[
					'screenId' => '8',
					'keyword_id' => 277,
					'keyword_name' => 'lblThirdDescriptions1',
					'keyword_value' => 'Home workouts with body weight exercises',
				],
				[
					'screenId' => '8',
					'keyword_id' => 278,
					'keyword_name' => 'lblThirdDescriptions2',
					'keyword_value' => 'Only exercises with dumbbell and body weight',
				],
				[
					'screenId' => '8',
					'keyword_id' => 279,
					'keyword_name' => 'lblThirdDescriptions3',
					'keyword_value' => 'Exercises with barbell,dumbbell and body weight',
				],
				[
					'screenId' => '8',
					'keyword_id' => 280,
					'keyword_name' => 'lblThirdDescriptions4',
					'keyword_value' => 'All exercises with machines,barbell and all',
				],
				[
					'screenId' => '8',
					'keyword_id' => 281,
					'keyword_name' => 'lblThirdDescriptions5',
					'keyword_value' => 'Choose the equipments you have or wish to use',
				],
				[
					'screenId' => '8',
					'keyword_id' => 282,
					'keyword_name' => 'lblHomeScreenTitle',
					'keyword_value' => 'Enter your height, weight, gender and age to access advanced features.',
				],
				[
					'screenId' => '8',
					'keyword_id' => 307,
					'keyword_name' => 'lblRepsWeight',
					'keyword_value' => 'Reps-Weight',
				],
				[
					'screenId' => '8',
					'keyword_id' => 309,
					'keyword_name' => 'lblLeaderboard',
					'keyword_value' => 'Leaderboard',
				],
				[
					'screenId' => '8',
					'keyword_id' => 308,
					'keyword_name' => 'lblRest',
					'keyword_value' => 'Rest',
				],
				[
					'screenId' => '8',
					'keyword_id' => 370,
					'keyword_name' => 'lblDailyTracking',
					'keyword_value' => 'Daily Tracking Progress',
				],
				[
					'screenId' => '8',
					'keyword_id' => 371,
					'keyword_name' => 'lblStpCnt',
					'keyword_value' => 'Steps Count',
				],
				[
					'screenId' => '8',
					'keyword_id' => 372,
					'keyword_name' => 'lblWtrInt',
					'keyword_value' => 'Water Intake',
				],
				[
					'screenId' => '8',
					'keyword_id' => 373,
					'keyword_name' => 'lblGlass',
					'keyword_value' => 'Glass',
				],
				[
					'screenId' => '8',
					'keyword_id' => 374,
					'keyword_name' => 'lblStpTrack',
					'keyword_value' => 'Step Tracker',
				],
				[
					'screenId' => '8',
					'keyword_id' => 375,
					'keyword_name' => 'lblStpC1',
					'keyword_value' => 'Steps are left to reach your goal!!!',
				],
				[
					'screenId' => '8',
					'keyword_id' => 376,
					'keyword_name' => 'lblOnly',
					'keyword_value' => 'Only',
				],
				[
					'screenId' => '8',
					'keyword_id' => 377,
					'keyword_name' => 'lblStpC2',
					'keyword_value' => 'Great! You reached your daily goal',
				],
				[
					'screenId' => '8',
					'keyword_id' => 378,
					'keyword_name' => 'lblStpC3',
					'keyword_value' => 'Please Set Your Goal First',
				],
				[
					'screenId' => '8',
					'keyword_id' => 379,
					'keyword_name' => 'lblStpC4',
					'keyword_value' => 'Amazing! Exceeded your goal by',
				],
				[
					'screenId' => '8',
					'keyword_id' => 380,
					'keyword_name' => 'lblDG',
					'keyword_value' => 'Daily Goal',
				],
				[
					'screenId' => '8',
					'keyword_id' => 381,
					'keyword_name' => 'lblWtrTrack',
					'keyword_value' => 'Water Tracker',
				],
				[
					'screenId' => '8',
					'keyword_id' => 382,
					'keyword_name' => 'lblGoalC1',
					'keyword_value' => 'glasses are left to reach your goal!!!',
				],
				[
					'screenId' => '8',
					'keyword_id' => 383,
					'keyword_name' => 'lblGlasses',
					'keyword_value' => 'Glasses',
				],
				[
					'screenId' => '8',
					'keyword_id' => 384,
					'keyword_name' => 'lblLogNw',
					'keyword_value' => 'Log Now',
				],
				[
					'screenId' => '8',
					'keyword_id' => 385,
					'keyword_name' => 'lblEnrGls',
					'keyword_value' => 'Enter glasses',
				],
				[
					'screenId' => '8',
					'keyword_id' => 386,
					'keyword_name' => 'lblWtrConsDaily',
					'keyword_value' => 'Water Consumption (Daily)',
				],
				[
					'screenId' => '8',
					'keyword_id' => 387,
					'keyword_name' => 'assignedWorkouts',
					'keyword_value' => 'Assigned Workouts',
				],
				[
					'screenId' => '8',
					'keyword_id' => 388,
					'keyword_name' => 'assignedDiet',
					'keyword_value' => 'Assigned Diet',
				],
			],
		],
		[
			'screenID' => '9',
			'ScreenName' => 'EditProfileScreen',
			'keyword_data' => [
				[
					'screenId' => '9',
					'keyword_id' => 58,
					'keyword_name' => 'lblEditProfile',
					'keyword_value' => 'Edit Profile',
				],
				[
					'screenId' => '9',
					'keyword_id' => 59,
					'keyword_name' => 'lblAge',
					'keyword_value' => 'Age',
				],
				[
					'screenId' => '9',
					'keyword_id' => 60,
					'keyword_name' => 'lblEnterAge',
					'keyword_value' => 'Enter Age',
				],
				[
					'screenId' => '9',
					'keyword_id' => 61,
					'keyword_name' => 'lblGender',
					'keyword_value' => 'Gender',
				],
				[
					'screenId' => '9',
					'keyword_id' => 62,
					'keyword_name' => 'lblSave',
					'keyword_value' => 'Save',
				],
				[
					'screenId' => '9',
					'keyword_id' => 215,
					'keyword_name' => 'lblTipsInst',
					'keyword_value' => 'Tips & Instructions',
				],
			],
		],
		[
			'screenID' => '10',
			'ScreenName' => 'NotificationScreen',
			'keyword_data' => [
				[
					'screenId' => '10',
					'keyword_id' => 63,
					'keyword_name' => 'lblNotifications',
					'keyword_value' => 'Notifications',
				],
				[
					'screenId' => '10',
					'keyword_id' => 64,
					'keyword_name' => 'lblNotificationEmpty',
					'keyword_value' => 'No New Notifications',
				],
				[
					'screenId' => '10',
					'keyword_id' => 210,
					'keyword_name' => 'lblRepeat',
					'keyword_value' => 'Repeat',
				],
			],
		],
		[
			'screenID' => '11',
			'ScreenName' => 'SearchScreen',
			'keyword_data' => [
				[
					'screenId' => '11',
					'keyword_id' => 65,
					'keyword_name' => 'lblSearchExercise',
					'keyword_value' => 'Search Exercise',
				],
				[
					'screenId' => '11',
					'keyword_id' => 66,
					'keyword_name' => 'lblExerciseNoFound',
					'keyword_value' => 'Sorry, No Exercise Found',
				],
				[
					'screenId' => '11',
					'keyword_id' => 67,
					'keyword_name' => 'lblAll',
					'keyword_value' => 'All',
				],
				[
					'screenId' => '11',
					'keyword_id' => 68,
					'keyword_name' => 'lblNoFoundData',
					'keyword_value' => 'No Data Found',
				],
				[
					'screenId' => '11',
					'keyword_id' => 69,
					'keyword_name' => 'lblDuration',
					'keyword_value' => 'Duration',
				],
			],
		],
		[
			'screenID' => '12',
			'ScreenName' => 'SubscribeScreen',
			'keyword_data' => [
				[
					'screenId' => '12',
					'keyword_id' => 70,
					'keyword_name' => 'lblPackageTitle',
					'keyword_value' => 'Be Premium Get Unlimited Access',
				],
				[
					'screenId' => '12',
					'keyword_id' => 71,
					'keyword_name' => 'lblPackageTitle1',
					'keyword_value' => 'Enjoy Workout Access Without Ads And Restrictions',
				],
				[
					'screenId' => '12',
					'keyword_id' => 72,
					'keyword_name' => 'lblMonth',
					'keyword_value' => 'Month',
				],
				[
					'screenId' => '12',
					'keyword_id' => 73,
					'keyword_name' => 'lblYear',
					'keyword_value' => 'year',
				],
				[
					'screenId' => '12',
					'keyword_id' => 74,
					'keyword_name' => 'lblSubscribe',
					'keyword_value' => 'Subscribe',
				],
				[
					'screenId' => '12',
					'keyword_id' => 75,
					'keyword_name' => 'lblSelectPlanToContinue',
					'keyword_value' => 'Select a Plan to Continue',
				],
				[
					'screenId' => '12',
					'keyword_id' => 76,
					'keyword_name' => 'lblSubscriptionPlans',
					'keyword_value' => 'Subscription Plans',
				],
				[
					'screenId' => '12',
					'keyword_id' => 77,
					'keyword_name' => 'lblActive',
					'keyword_value' => 'Active',
				],
				[
					'screenId' => '12',
					'keyword_id' => 78,
					'keyword_name' => 'lblHistory',
					'keyword_value' => 'History',
				],
				[
					'screenId' => '12',
					'keyword_id' => 79,
					'keyword_name' => 'lblSubscriptionMsg',
					'keyword_value' => 'You Haven\'t Subscribed Yet',
				],
				[
					'screenId' => '12',
					'keyword_id' => 80,
					'keyword_name' => 'lblViewPlans',
					'keyword_value' => 'View Plans',
				],
				[
					'screenId' => '12',
					'keyword_id' => 81,
					'keyword_name' => 'lblYourPlanValid',
					'keyword_value' => 'your plan valid',
				],
				[
					'screenId' => '12',
					'keyword_id' => 82,
					'keyword_name' => 'lblCancelSubscription',
					'keyword_value' => 'Cancel Subscription',
				],
				[
					'screenId' => '12',
					'keyword_id' => 83,
					'keyword_name' => 'lblTo',
					'keyword_value' => 'Top Fitness Reads',
				],
				[
					'screenId' => '12',
					'keyword_id' => 201,
					'keyword_name' => 'lblBuyNow',
					'keyword_value' => 'Buy Now',
				],
				[
					'screenId' => '12',
					'keyword_id' => 203,
					'keyword_name' => 'lblBmi',
					'keyword_value' => 'BMI',
				],
			],
		],
		[
			'screenID' => '13',
			'ScreenName' => 'ExerciseDetailScreen',
			'keyword_data' => [
				[
					'screenId' => '13',
					'keyword_id' => 84,
					'keyword_name' => 'lblNoSetsMsg',
					'keyword_value' => 'Can not go forward due to blank sets',
				],
				[
					'screenId' => '13',
					'keyword_id' => 85,
					'keyword_name' => 'lblStartExercise',
					'keyword_value' => 'Start Exercise',
				],
				[
					'screenId' => '13',
					'keyword_id' => 86,
					'keyword_name' => 'lblBodyParts',
					'keyword_value' => 'Body Parts',
				],
				[
					'screenId' => '13',
					'keyword_id' => 87,
					'keyword_name' => 'lblEquipments',
					'keyword_value' => 'Equipment\'s',
				],
				[
					'screenId' => '13',
					'keyword_id' => 218,
					'keyword_name' => 'lblSets',
					'keyword_value' => 'Sets',
				],
				[
					'screenId' => '13',
					'keyword_id' => 219,
					'keyword_name' => 'lblReps',
					'keyword_value' => 'Reps',
				],
				[
					'screenId' => '13',
					'keyword_id' => 220,
					'keyword_name' => 'lblSecond',
					'keyword_value' => 'Second',
				],
				[
					'screenId' => '13',
					'keyword_id' => 222,
					'keyword_name' => 'lblTenSecondRemaining',
					'keyword_value' => 'ten second remaining',
				],
				[
					'screenId' => '13',
					'keyword_id' => 223,
					'keyword_name' => 'lblThree',
					'keyword_value' => 'Three',
				],
				[
					'screenId' => '13',
					'keyword_id' => 224,
					'keyword_name' => 'lblTwo',
					'keyword_value' => 'Two',
				],
				[
					'screenId' => '13',
					'keyword_id' => 225,
					'keyword_name' => 'lblOne',
					'keyword_value' => 'One',
				],
				[
					'screenId' => '13',
					'keyword_id' => 226,
					'keyword_name' => 'lblEnterReminderName',
					'keyword_value' => 'Enter Reminder Name',
				],
				[
					'screenId' => '13',
					'keyword_id' => 227,
					'keyword_name' => 'lblEnterDescription',
					'keyword_value' => 'Enter Description',
				],
				[
					'screenId' => '13',
					'keyword_id' => 389,
					'keyword_name' => 'resetExercise',
					'keyword_value' => 'Reset Exercise',
				],
				[
					'screenId' => '13',
					'keyword_id' => 390,
					'keyword_name' => 'lblComplete',
					'keyword_value' => 'Complete',
				],
				[
					'screenId' => '13',
					'keyword_id' => 391,
					'keyword_name' => 'lblUpNext',
					'keyword_value' => 'Up Next',
				],
				[
					'screenId' => '13',
					'keyword_id' => 392,
					'keyword_name' => 'confirmCompleteExercise',
					'keyword_value' => 'Are you certain you wish to complete this exercise?',
				],
				[
					'screenId' => '13',
					'keyword_id' => 240,
					'keyword_name' => 'lblExerciseDone',
					'keyword_value' => 'Exercise Done',
				],
			],
		],
		[
			'screenID' => '14',
			'ScreenName' => 'PaymentScreen',
			'keyword_data' => [
				[
					'screenId' => '14',
					'keyword_id' => 88,
					'keyword_name' => 'lblSuccess',
					'keyword_value' => 'Success',
				],
				[
					'screenId' => '14',
					'keyword_id' => 89,
					'keyword_name' => 'lblSuccessMsg',
					'keyword_value' => 'Successfully Done:)',
				],
				[
					'screenId' => '14',
					'keyword_id' => 90,
					'keyword_name' => 'lblPaymentFailed',
					'keyword_value' => 'Payment Failed',
				],
				[
					'screenId' => '14',
					'keyword_id' => 91,
					'keyword_name' => 'lblPayments',
					'keyword_value' => 'Payments',
				],
				[
					'screenId' => '14',
					'keyword_id' => 92,
					'keyword_name' => 'lblPay',
					'keyword_value' => 'Pay',
				],
				[
					'screenId' => '14',
					'keyword_id' => 294,
					'keyword_name' => 'lblFailed',
					'keyword_value' => 'Failed',
				],
				[
					'screenId' => '14',
					'keyword_id' => 295,
					'keyword_name' => 'lblPaymentSuccessful',
					'keyword_value' => 'Payment Successful!',
				],
				[
					'screenId' => '14',
					'keyword_id' => 296,
					'keyword_name' => 'lblPaymentCancelled',
					'keyword_value' => 'Payment Cancelled!',
				],
			],
		],
		[
			'screenID' => '15',
			'ScreenName' => 'FilterWorkoutScreen',
			'keyword_data' => [
				[
					'screenId' => '15',
					'keyword_id' => 92,
					'keyword_name' => 'lblWorkoutType',
					'keyword_value' => 'Workout Type',
				],
				[
					'screenId' => '15',
					'keyword_id' => 93,
					'keyword_name' => 'lblWorkoutLevel',
					'keyword_value' => 'Workout Level',
				],
				[
					'screenId' => '15',
					'keyword_id' => 204,
					'keyword_name' => 'lblFullBodyWorkout',
					'keyword_value' => 'Full Body Workout',
				],
				[
					'screenId' => '15',
					'keyword_id' => 205,
					'keyword_name' => 'lblTypes',
					'keyword_value' => 'Type\'s',
				],
				[
					'screenId' => '15',
					'keyword_id' => 206,
					'keyword_name' => 'lblClearAll',
					'keyword_value' => 'Cancel All',
				],
				[
					'screenId' => '15',
					'keyword_id' => 207,
					'keyword_name' => 'lblSelectAll',
					'keyword_value' => 'Select All',
				],
				[
					'screenId' => '15',
					'keyword_id' => 208,
					'keyword_name' => 'lblShowResult',
					'keyword_value' => 'Show Result',
				],
				[
					'screenId' => '15',
					'keyword_id' => 209,
					'keyword_name' => 'lblSelectLevels',
					'keyword_value' => 'Select Levels',
				],
				[
					'screenId' => '15',
					'keyword_id' => 221,
					'keyword_name' => 'lblWorkoutNoFound',
					'keyword_value' => 'Sorry, No Workout Found',
				],
			],
		],
		[
			'screenID' => '16',
			'ScreenName' => 'DietScreen',
			'keyword_data' => [
				[
					'screenId' => '16',
					'keyword_id' => 94,
					'keyword_name' => 'lblDietCategories',
					'keyword_value' => 'Diet Categories',
				],
				[
					'screenId' => '16',
					'keyword_id' => 95,
					'keyword_name' => 'lblBestDietDiscoveries',
					'keyword_value' => 'Best Diet Discoveries',
				],
				[
					'screenId' => '16',
					'keyword_id' => 96,
					'keyword_name' => 'lblDietaryOptions',
					'keyword_value' => 'Dietary Options',
				],
				[
					'screenId' => '16',
					'keyword_id' => 97,
					'keyword_name' => 'lblResultNoFound',
					'keyword_value' => 'Sorry, No Results Found',
				],
				[
					'screenId' => '16',
					'keyword_id' => 363,
					'keyword_name' => 'disclaimer',
					'keyword_value' => 'Disclaimer',
				],
				[
					'screenId' => '16',
					'keyword_id' => 364,
					'keyword_name' => 'viewSourceReference',
					'keyword_value' => 'View Sources & References',
				],
				[
					'screenId' => '16',
					'keyword_id' => 365,
					'keyword_name' => 'sourceReference',
					'keyword_value' => 'Sources & References',
				],
				[
					'screenId' => '16',
					'keyword_id' => 366,
					'keyword_name' => 'close',
					'keyword_value' => 'Close',
				],
				[
					'screenId' => '16',
					'keyword_id' => 367,
					'keyword_name' => 'dietDesclaimerNote',
					'keyword_value' => 'This app provides general health and nutrition information and is not intended to replace professional medical advice. ',
				],
				[
					'screenId' => '16',
					'keyword_id' => 368,
					'keyword_name' => 'dietDesclaimerNote2',
					'keyword_value' => ' Dietary needs vary, and you should consult a healthcare professional before making significant dietary changes.',
				],
				[
					'screenId' => '16',
					'keyword_id' => 369,
					'keyword_name' => 'dietDesclaimerNote3',
					'keyword_value' => ' The information presented is based on available research and should not be considered medical advice.',
				],
			],
		],
		[
			'screenID' => '17',
			'ScreenName' => 'ProductScreen',
			'keyword_data' => [
				[
					'screenId' => '17',
					'keyword_id' => 98,
					'keyword_name' => 'lblProductCategory',
					'keyword_value' => 'Fitness Accessory Category',
				],
				[
					'screenId' => '17',
					'keyword_id' => 99,
					'keyword_name' => 'lblProductList',
					'keyword_value' => 'Fitness Accessorie',
				],
				[
					'screenId' => '17',
					'keyword_id' => 100,
					'keyword_name' => 'lblBreak',
					'keyword_value' => 'Blissful Break 😊',
				],
			],
		],
		[
			'screenID' => '18',
			'ScreenName' => 'ProgressScreen',
			'keyword_data' => [
				[
					'screenId' => '18',
					'keyword_id' => 101,
					'keyword_name' => 'lblHeartRate',
					'keyword_value' => 'Heart Rate',
				],
				[
					'screenId' => '18',
					'keyword_id' => 102,
					'keyword_name' => 'lblPushUp',
					'keyword_value' => 'Push ups in 1 minute',
				],
				[
					'screenId' => '18',
					'keyword_id' => 103,
					'keyword_name' => 'lblupdate',
					'keyword_value' => 'Update',
				],
				[
					'screenId' => '18',
					'keyword_id' => 104,
					'keyword_name' => 'lblHint',
					'keyword_value' => '50',
				],
				[
					'screenId' => '18',
					'keyword_id' => 105,
					'keyword_name' => 'lblDate',
					'keyword_value' => 'Date',
				],
				[
					'screenId' => '18',
					'keyword_id' => 106,
					'keyword_name' => 'lblDelete',
					'keyword_value' => 'Delete',
				],
				[
					'screenId' => '18',
					'keyword_id' => 107,
					'keyword_name' => 'lblDeleteAccountMSg',
					'keyword_value' => 'Are you sure you want to delete the',
				],
				[
					'screenId' => '18',
					'keyword_id' => 108,
					'keyword_name' => 'lblDeleteMsg',
					'keyword_value' => 'Are you certain you wish to permanently remove your account?',
				],
				[
					'screenId' => '18',
					'keyword_id' => 109,
					'keyword_name' => 'lblDeleteAccount',
					'keyword_value' => 'Delete Account',
				],
				[
					'screenId' => '18',
					'keyword_id' => 216,
					'keyword_name' => 'lblAdd',
					'keyword_value' => 'Add',
				],
				[
					'screenId' => '18',
					'keyword_id' => 239,
					'keyword_name' => 'lblSteps',
					'keyword_value' => 'Steps',
				],
				[
					'screenId' => '18',
					'keyword_id' => 395,
					'keyword_name' => 'lblGoal',
					'keyword_value' => 'Goal',
				],
				[
					'screenId' => '18',
					'keyword_id' => 396,
					'keyword_name' => 'lblAchived',
					'keyword_value' => 'Achieved',
				],
				[
					'screenId' => '18',
					'keyword_id' => 397,
					'keyword_name' => 'lblConsumed',
					'keyword_value' => 'Consumed',
				],
				[
					'screenId' => '18',
					'keyword_id' => 398,
					'keyword_name' => 'valueGreaterZero',
					'keyword_value' => 'Value must be greater than 0',
				],
			],
		],
		[
			'screenID' => '19',
			'ScreenName' => 'ProfileScreen',
			'keyword_data' => [
				[
					'screenId' => '19',
					'keyword_id' => 110,
					'keyword_name' => 'lblBlog',
					'keyword_value' => 'Blogs',
				],
				[
					'screenId' => '19',
					'keyword_id' => 111,
					'keyword_name' => 'lblFavoriteWorkoutAndNutristions',
					'keyword_value' => 'Favorites Workout & Nutrition',
				],
				[
					'screenId' => '19',
					'keyword_id' => 112,
					'keyword_name' => 'lblDailyReminders',
					'keyword_value' => 'Daily Reminders',
				],
				[
					'screenId' => '19',
					'keyword_id' => 113,
					'keyword_name' => 'lblPlan',
					'keyword_value' => 'Assigned Workout & Diet',
				],
				[
					'screenId' => '19',
					'keyword_id' => 114,
					'keyword_name' => 'lblSettings',
					'keyword_value' => 'Settings',
				],
				[
					'screenId' => '19',
					'keyword_id' => 115,
					'keyword_name' => 'lblAboutApp',
					'keyword_value' => 'About App',
				],
				[
					'screenId' => '19',
					'keyword_id' => 116,
					'keyword_name' => 'lblLogout',
					'keyword_value' => 'Logout',
				],
				[
					'screenId' => '19',
					'keyword_id' => 117,
					'keyword_name' => 'lblLogoutMsg',
					'keyword_value' => 'Are you certain you wish to log out now?',
				],
				[
					'screenId' => '19',
					'keyword_id' => 118,
					'keyword_name' => 'lblPrivacyPolicy',
					'keyword_value' => 'Privacy Policy',
				],
				[
					'screenId' => '19',
					'keyword_id' => 119,
					'keyword_name' => 'lblTermsOfServices',
					'keyword_value' => 'Terms of Service',
				],
				[
					'screenId' => '19',
					'keyword_id' => 120,
					'keyword_name' => 'lblAboutUs',
					'keyword_value' => 'About Us',
				],
				[
					'screenId' => '19',
					'keyword_id' => 121,
					'keyword_name' => 'lblTopFitnessReads',
					'keyword_value' => 'Top Fitness Reads',
				],
				[
					'screenId' => '19',
					'keyword_id' => 122,
					'keyword_name' => 'lblTrendingBlogs',
					'keyword_value' => 'Trending Blogs',
				],
				[
					'screenId' => '19',
					'keyword_id' => 123,
					'keyword_name' => 'lblBlogNoFound',
					'keyword_value' => 'Sorry, No Blog Found',
				],
				[
					'screenId' => '19',
					'keyword_id' => 124,
					'keyword_name' => 'lblFollowUs',
					'keyword_value' => 'Follow Us',
				],
				[
					'screenId' => '19',
					'keyword_id' => 211,
					'keyword_name' => 'lblEveryday',
					'keyword_value' => 'Everyday',
				],
				[
					'screenId' => '19',
					'keyword_id' => 212,
					'keyword_name' => 'lblReminderName',
					'keyword_value' => 'Reminder name',
				],
				[
					'screenId' => '19',
					'keyword_id' => 213,
					'keyword_name' => 'lblDescription',
					'keyword_value' => 'Description',
				],
				[
					'screenId' => '19',
					'keyword_id' => 354,
					'keyword_name' => 'lblPostBmk',
					'keyword_value' => 'Post Bookmark',
				],
				[
					'screenId' => '19',
					'keyword_id' => 355,
					'keyword_name' => 'lblWOHtr',
					'keyword_value' => 'Workout History',
				],
				[
					'screenId' => '19',
					'keyword_id' => 393,
					'keyword_name' => 'lblExerHtr',
					'keyword_value' => 'Exercise History',
				],
			],
		],
		[
			'screenID' => '20',
			'ScreenName' => 'SettingScreen',
			'keyword_data' => [
				[
					'screenId' => '20',
					'keyword_id' => 125,
					'keyword_name' => 'lblMetricsSettings',
					'keyword_value' => 'Metrics Settings',
				],
				[
					'screenId' => '20',
					'keyword_id' => 126,
					'keyword_name' => 'lblSelectLanguage',
					'keyword_value' => 'Choose Language',
				],
				[
					'screenId' => '20',
					'keyword_id' => 127,
					'keyword_name' => 'lblAppThemes',
					'keyword_value' => 'App Themes',
				],
				[
					'screenId' => '20',
					'keyword_id' => 128,
					'keyword_name' => 'lblChangePassword',
					'keyword_value' => 'AChange Password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 129,
					'keyword_name' => 'lblLight',
					'keyword_value' => 'Light',
				],
				[
					'screenId' => '20',
					'keyword_id' => 130,
					'keyword_name' => 'lblDark',
					'keyword_value' => 'Dark',
				],
				[
					'screenId' => '20',
					'keyword_id' => 131,
					'keyword_name' => 'lblSystemDefault',
					'keyword_value' => 'System Default',
				],
				[
					'screenId' => '20',
					'keyword_id' => 132,
					'keyword_name' => 'lblSelectTheme',
					'keyword_value' => 'Theme',
				],
				[
					'screenId' => '20',
					'keyword_id' => 133,
					'keyword_name' => 'lblCurrentPassword',
					'keyword_value' => 'Current Password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 134,
					'keyword_name' => 'lblEnterCurrentPwd',
					'keyword_value' => 'Enter Current Password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 135,
					'keyword_name' => 'lblNewPassword',
					'keyword_value' => 'New Password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 136,
					'keyword_name' => 'lblPasswordMsg',
					'keyword_value' => 'Your new password must be different from old password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 137,
					'keyword_name' => 'lblEnterNewPwd',
					'keyword_value' => 'Enter New Password',
				],
				[
					'screenId' => '20',
					'keyword_id' => 139,
					'keyword_name' => 'lblSubmit',
					'keyword_value' => 'Submit',
				],
				[
					'screenId' => '20',
					'keyword_id' => 140,
					'keyword_name' => 'lblIdealWeight',
					'keyword_value' => 'Ideal weight',
				],
				[
					'screenId' => '20',
					'keyword_id' => 141,
					'keyword_name' => 'lblBmr',
					'keyword_value' => 'BMR',
				],
				[
					'screenId' => '20',
					'keyword_id' => 142,
					'keyword_name' => 'lblTotalSteps',
					'keyword_value' => 'Total steps',
				],
				[
					'screenId' => '20',
					'keyword_id' => 200,
					'keyword_name' => 'lblForgotPwdMsg',
					'keyword_value' => 'Please enter your email address to request a password reset',
				],
				[
					'screenId' => '20',
					'keyword_id' => 236,
					'keyword_name' => 'lblCancel',
					'keyword_value' => 'Cancel',
				],
			],
		],
		[
			'screenID' => '21',
			'ScreenName' => 'ChattingImageScreen',
			'keyword_data' => [
				[
					'screenId' => '21',
					'keyword_id' => 143,
					'keyword_name' => 'lblChatConfirmMsg',
					'keyword_value' => 'Do you want to clear the conversations ?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 144,
					'keyword_name' => 'lblYes',
					'keyword_value' => 'Yes',
				],
				[
					'screenId' => '21',
					'keyword_id' => 145,
					'keyword_name' => 'lblNo',
					'keyword_value' => 'No',
				],
				[
					'screenId' => '21',
					'keyword_id' => 146,
					'keyword_name' => 'lblFitBot',
					'keyword_value' => 'FitBot',
				],
				[
					'screenId' => '21',
					'keyword_id' => 147,
					'keyword_name' => 'lblClearConversion',
					'keyword_value' => 'Clear Conversion',
				],
				[
					'screenId' => '21',
					'keyword_id' => 148,
					'keyword_name' => 'lblChatHintText',
					'keyword_value' => 'How can i help you...',
				],
				[
					'screenId' => '21',
					'keyword_id' => 149,
					'keyword_name' => 'lblCopiedToClipboard',
					'keyword_value' => 'Copied to Clipboard',
				],
				[
					'screenId' => '21',
					'keyword_id' => 150,
					'keyword_name' => 'lblQue1',
					'keyword_value' => 'How can I start a fitness routine as a beginner?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 151,
					'keyword_name' => 'lblQue2',
					'keyword_value' => 'What are some healthy nutrition tips for fitness and weight management?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 152,
					'keyword_name' => 'lblQue3',
					'keyword_value' => 'What\'s the best way to lose weight through exercise and diet?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 153,
					'keyword_name' => 'lblG',
					'keyword_value' => 'g',
				],
				[
					'screenId' => '21',
					'keyword_id' => 154,
					'keyword_name' => 'lblMainGoal',
					'keyword_value' => 'What is your main goal?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 155,
					'keyword_name' => 'lblHowExperienced',
					'keyword_value' => 'How experienced are you with fitness?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 157,
					'keyword_name' => 'lblHoweEquipment',
					'keyword_value' => 'What equipments do you have?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 158,
					'keyword_name' => 'lblHoweOftenWorkout',
					'keyword_value' => 'How often do you want to workout?',
				],
				[
					'screenId' => '21',
					'keyword_id' => 245,
					'keyword_name' => 'lblFinish',
					'keyword_value' => 'Finish',
				],
				[
					'screenId' => '21',
					'keyword_id' => 160,
					'keyword_name' => 'lblProgression',
					'keyword_value' => 'Progression',
				],
				[
					'screenId' => '21',
					'keyword_id' => 161,
					'keyword_name' => 'lblEasyHabit',
					'keyword_value' => 'Easy to form habit',
				],
				[
					'screenId' => '21',
					'keyword_id' => 162,
					'keyword_name' => 'lblRecommend',
					'keyword_value' => 'We recommend',
				],
				[
					'screenId' => '21',
					'keyword_id' => 163,
					'keyword_name' => 'lblTimesWeek',
					'keyword_value' => 'times/week want to workout',
				],
				[
					'screenId' => '21',
					'keyword_id' => 164,
					'keyword_name' => 'lblOnlyTimesWeek',
					'keyword_value' => 'times/week',
				],
				[
					'screenId' => '21',
					'keyword_id' => 165,
					'keyword_name' => 'lblUsernameShouldNotContainSpace',
					'keyword_value' => 'Username should not contain space',
				],
				[
					'screenId' => '21',
					'keyword_id' => 166,
					'keyword_name' => 'lblMinimumPasswordLengthShouldBe',
					'keyword_value' => 'Minimum password length should be',
				],
				[
					'screenId' => '21',
					'keyword_id' => 167,
					'keyword_name' => 'lblInternetIsConnected',
					'keyword_value' => 'Internet is connected.',
				],
				[
					'screenId' => '21',
					'keyword_id' => 168,
					'keyword_name' => 'lblNoDurationMsg',
					'keyword_value' => 'Can not go forward due to blank duration',
				],
				[
					'screenId' => '21',
					'keyword_id' => 170,
					'keyword_name' => 'lblErrorNotAllow',
					'keyword_value' => 'Sorry, You are not allowed',
				],
				[
					'screenId' => '21',
					'keyword_id' => 171,
					'keyword_name' => 'lblPleaseTryAgain',
					'keyword_value' => 'Please try again',
				],
				[
					'screenId' => '21',
					'keyword_id' => 172,
					'keyword_name' => 'lblInvalidUrl',
					'keyword_value' => 'Invalid URL',
				],
				[
					'screenId' => '21',
					'keyword_id' => 173,
					'keyword_name' => 'lblCalories',
					'keyword_value' => 'Calories',
				],
				[
					'screenId' => '21',
					'keyword_id' => 174,
					'keyword_name' => 'lblCarbs',
					'keyword_value' => 'Carbs',
				],
				[
					'screenId' => '21',
					'keyword_id' => 175,
					'keyword_name' => 'lblFat',
					'keyword_value' => 'Fat',
				],
				[
					'screenId' => '21',
					'keyword_id' => 176,
					'keyword_name' => 'lblProtein',
					'keyword_value' => 'Protein',
				],
				[
					'screenId' => '21',
					'keyword_id' => 178,
					'keyword_name' => 'lblKcal',
					'keyword_value' => 'Kcal',
				],
				[
					'screenId' => '21',
					'keyword_id' => 179,
					'keyword_name' => 'lblIngredients',
					'keyword_value' => 'Ingredients',
				],
				[
					'screenId' => '21',
					'keyword_id' => 180,
					'keyword_name' => 'lblInstruction',
					'keyword_value' => 'Instruction',
				],
				[
					'screenId' => '21',
					'keyword_id' => 181,
					'keyword_name' => 'lblNoInternet',
					'keyword_value' => 'No Internet',
				],
				[
					'screenId' => '21',
					'keyword_id' => 234,
					'keyword_name' => 'lblFavourite',
					'keyword_value' => 'Favourite',
				],
				[
					'screenId' => '21',
					'keyword_id' => 235,
					'keyword_name' => 'lblStore',
					'keyword_value' => 'Store',
				],
				[
					'screenId' => '21',
					'keyword_id' => 237,
					'keyword_name' => 'lblPro',
					'keyword_value' => 'Pro',
				],
				[
					'screenId' => '21',
					'keyword_id' => 283,
					'keyword_name' => 'lblNoConversationFound',
					'keyword_value' => 'No Conversation Found',
				],
				[
					'screenId' => '21',
					'keyword_id' => 284,
					'keyword_name' => 'lblViewContact',
					'keyword_value' => 'View Contact',
				],
				[
					'screenId' => '21',
					'keyword_id' => 285,
					'keyword_name' => 'lblUnblock',
					'keyword_value' => 'Unblock',
				],
				[
					'screenId' => '21',
					'keyword_id' => 286,
					'keyword_name' => 'lblBlock',
					'keyword_value' => 'Block',
				],
				[
					'screenId' => '21',
					'keyword_id' => 287,
					'keyword_name' => 'lblClearChat',
					'keyword_value' => 'Clear Chat',
				],
				[
					'screenId' => '21',
					'keyword_id' => 288,
					'keyword_name' => 'lblChatCleared',
					'keyword_value' => 'Chat cleared',
				],
				[
					'screenId' => '21',
					'keyword_id' => 289,
					'keyword_name' => 'lblBlockMsg',
					'keyword_value' => 'Blocked contact will no longer be able to call you or send you messages.',
				],
				[
					'screenId' => '21',
					'keyword_id' => 290,
					'keyword_name' => 'lblOnline',
					'keyword_value' => 'Online',
				],
				[
					'screenId' => '21',
					'keyword_id' => 291,
					'keyword_name' => 'lblLastSeen',
					'keyword_value' => 'Last seen',
				],
				[
					'screenId' => '21',
					'keyword_id' => 292,
					'keyword_name' => 'lblSearchHere',
					'keyword_value' => 'Search Here',
				],
				[
					'screenId' => '21',
					'keyword_id' => 293,
					'keyword_name' => 'lblNewChat',
					'keyword_value' => 'New Chat',
				],
				[
					'screenId' => '21',
					'keyword_id' => 297,
					'keyword_name' => 'lblDeleteChat',
					'keyword_value' => 'Delete Chat',
				],
				[
					'screenId' => '21',
					'keyword_id' => 298,
					'keyword_name' => 'lblDeleteDialogTitle',
					'keyword_value' => 'All Chat will be cleared and deleted',
				],
				[
					'screenId' => '21',
					'keyword_id' => 299,
					'keyword_name' => 'lblChatDeleted',
					'keyword_value' => 'Chat Deleted',
				],
				[
					'screenId' => '21',
					'keyword_id' => 300,
					'keyword_name' => 'lblDeleteMessage',
					'keyword_value' => 'Delete Message',
				],
				[
					'screenId' => '21',
					'keyword_id' => 301,
					'keyword_name' => 'lblChat',
					'keyword_value' => 'Chat',
				],
				[
					'screenId' => '21',
					'keyword_id' => 302,
					'keyword_name' => 'lblMinRead',
					'keyword_value' => 'min read',
				],
				[
					'screenId' => '21',
					'keyword_id' => 305,
					'keyword_name' => 'lblToSendMsg',
					'keyword_value' => 'to send a message',
				],
				[
					'screenId' => '21',
					'keyword_id' => 306,
					'keyword_name' => 'lblMsg',
					'keyword_value' => 'Message',
				],
			],
		],
		[
			'screenID' => '22',
			'ScreenName' => 'OTPScreen',
			'keyword_data' => [
				[
					'screenId' => '22',
					'keyword_id' => 190,
					'keyword_name' => 'lblContinueWithPhone',
					'keyword_value' => 'Continue with Phone',
				],
				[
					'screenId' => '22',
					'keyword_id' => 191,
					'keyword_name' => 'lblRcvCode',
					'keyword_value' => 'You\'ll receive 6 digit code to verify next.',
				],
				[
					'screenId' => '22',
					'keyword_id' => 192,
					'keyword_name' => 'lblVerifyOTP',
					'keyword_value' => 'OTP Verification',
				],
				[
					'screenId' => '22',
					'keyword_id' => 193,
					'keyword_name' => 'lblVerifyProceed',
					'keyword_value' => 'Verify & Proceed',
				],
				[
					'screenId' => '22',
					'keyword_id' => 194,
					'keyword_name' => 'lblCode',
					'keyword_value' => 'We have sent the code verification to',
				],
				[
					'screenId' => '22',
					'keyword_id' => 195,
					'keyword_name' => 'lblMonthly',
					'keyword_value' => 'Monthly',
				],
				[
					'screenId' => '22',
					'keyword_id' => 214,
					'keyword_name' => 'lblFav',
					'keyword_value' => 'Preferred Workouts & Nutrition',
				],
				[
					'screenId' => '22',
					'keyword_id' => 217,
					'keyword_name' => 'lblEnterText',
					'keyword_value' => 'Please enter some text',
				],
				[
					'screenId' => '22',
					'keyword_id' => 228,
					'keyword_name' => 'lblErrorThisFiledIsRequired',
					'keyword_value' => 'This field is required',
				],
				[
					'screenId' => '22',
					'keyword_id' => 229,
					'keyword_name' => 'lblSomethingWentWrong',
					'keyword_value' => 'Something Went Wrong',
				],
				[
					'screenId' => '22',
					'keyword_id' => 230,
					'keyword_name' => 'lblErrorInternetNotAvailable',
					'keyword_value' => 'Your internet is not working',
				],
				[
					'screenId' => '22',
					'keyword_id' => 233,
					'keyword_name' => 'lblContinue',
					'keyword_value' => 'Continue',
				],
			],
		],
		[
			'screenID' => '23',
			'ScreenName' => 'ScheduleScreen',
			'keyword_data' => [
				[
					'screenId' => '23',
					'keyword_id' => 242,
					'keyword_name' => 'lblSchedule',
					'keyword_value' => 'Schedule',
				],
				[
					'screenId' => '23',
					'keyword_id' => 243,
					'keyword_name' => 'lblChangeView',
					'keyword_value' => 'Change calendar view',
				],
				[
					'screenId' => '23',
					'keyword_id' => 244,
					'keyword_name' => 'lblJoin',
					'keyword_value' => 'Join',
				],
				[
					'screenId' => '23',
					'keyword_id' => 303,
					'keyword_name' => 'lblFree',
					'keyword_value' => 'Free',
				],
				[
					'screenId' => '23',
					'keyword_id' => 304,
					'keyword_name' => 'lblPurchases',
					'keyword_value' => 'Purchases',
				],
			],
		],
		[
			'screenID' => '24',
			'ScreenName' => 'CommunityScreen',
			'keyword_data' => [
				[
					'screenId' => '24',
					'keyword_id' => 310,
					'keyword_name' => 'lblCommunity',
					'keyword_value' => 'Community',
				],
				[
					'screenId' => '24',
					'keyword_id' => 311,
					'keyword_name' => 'lblReportPost',
					'keyword_value' => 'Report this post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 312,
					'keyword_name' => 'lblEditPost',
					'keyword_value' => 'Edit Post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 313,
					'keyword_name' => 'lblDeletePost',
					'keyword_value' => 'Are you sure you want to delete this post?',
				],
				[
					'screenId' => '24',
					'keyword_id' => 314,
					'keyword_name' => 'lblDelPost',
					'keyword_value' => 'Delete Post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 315,
					'keyword_name' => 'gotoProfile',
					'keyword_value' => 'Go to Profile',
				],
				[
					'screenId' => '24',
					'keyword_id' => 316,
					'keyword_name' => 'lblNoPost',
					'keyword_value' => 'No post available.',
				],
				[
					'screenId' => '24',
					'keyword_id' => 317,
					'keyword_name' => 'lblComments',
					'keyword_value' => 'Comments',
				],
				[
					'screenId' => '24',
					'keyword_id' => 318,
					'keyword_name' => 'lblUpdate',
					'keyword_value' => 'Update',
				],
				[
					'screenId' => '24',
					'keyword_id' => 319,
					'keyword_name' => 'lblReply',
					'keyword_value' => 'Reply',
				],
				[
					'screenId' => '24',
					'keyword_id' => 320,
					'keyword_name' => 'lblViewR',
					'keyword_value' => 'view reply',
				],
				[
					'screenId' => '24',
					'keyword_id' => 321,
					'keyword_name' => 'lblHideR',
					'keyword_value' => 'hide reply',
				],
				[
					'screenId' => '24',
					'keyword_id' => 322,
					'keyword_name' => 'lblUpComments',
					'keyword_value' => 'Update Comment',
				],
				[
					'screenId' => '24',
					'keyword_id' => 323,
					'keyword_name' => 'lblAddComments',
					'keyword_value' => 'Add a comment',
				],
				[
					'screenId' => '24',
					'keyword_id' => 324,
					'keyword_name' => 'lblReports',
					'keyword_value' => 'Report',
				],
				[
					'screenId' => '24',
					'keyword_id' => 325,
					'keyword_name' => 'lblRepoDes',
					'keyword_value' => 'Report Description',
				],
				[
					'screenId' => '24',
					'keyword_id' => 327,
					'keyword_name' => 'lblRepo',
					'keyword_value' => 'Reported:',
				],
				[
					'screenId' => '24',
					'keyword_id' => 328,
					'keyword_name' => 'finishProfileSetting',
					'keyword_value' => 'Finish setting up your profile',
				],
				[
					'screenId' => '24',
					'keyword_id' => 326,
					'keyword_name' => 'lblChoseVideo',
					'keyword_value' => 'Choose Video',
				],
				[
					'screenId' => '24',
					'keyword_id' => 329,
					'keyword_name' => 'lblMaxVideoMsg',
					'keyword_value' => 'Video size exceeds 30 MB. Please select a smaller video.',
				],
				[
					'screenId' => '24',
					'keyword_id' => 330,
					'keyword_name' => 'lblNewPost',
					'keyword_value' => 'New post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 331,
					'keyword_name' => 'WriteSomeThing',
					'keyword_value' => 'write something here....',
				],
				[
					'screenId' => '24',
					'keyword_id' => 332,
					'keyword_name' => 'lblEditImg',
					'keyword_value' => 'Edit Image',
				],
				[
					'screenId' => '24',
					'keyword_id' => 333,
					'keyword_name' => 'lblEditVid',
					'keyword_value' => 'Edit Video',
				],
				[
					'screenId' => '24',
					'keyword_id' => 334,
					'keyword_name' => 'lblSelectImg',
					'keyword_value' => 'Selected Image:',
				],
				[
					'screenId' => '24',
					'keyword_id' => 335,
					'keyword_name' => 'lblSelectVid',
					'keyword_value' => 'Video selected successfully.',
				],
				[
					'screenId' => '24',
					'keyword_id' => 336,
					'keyword_name' => 'lblEmptyMsg',
					'keyword_value' => 'Please add contain',
				],
				[
					'screenId' => '24',
					'keyword_id' => 337,
					'keyword_name' => 'lblAddImg',
					'keyword_value' => 'Add Image',
				],
				[
					'screenId' => '24',
					'keyword_id' => 338,
					'keyword_name' => 'lblAddVid',
					'keyword_value' => 'Add Video',
				],
				[
					'screenId' => '24',
					'keyword_id' => 339,
					'keyword_name' => 'lblSharePost',
					'keyword_value' => 'Share Post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 340,
					'keyword_name' => 'lblCamera',
					'keyword_value' => 'Camera',
				],
				[
					'screenId' => '24',
					'keyword_id' => 341,
					'keyword_name' => 'lblChoseImg',
					'keyword_value' => 'Choose image',
				],
				[
					'screenId' => '24',
					'keyword_id' => 342,
					'keyword_name' => 'lblRecord',
					'keyword_value' => 'Record',
				],
				[
					'screenId' => '24',
					'keyword_id' => 343,
					'keyword_name' => 'lblPost',
					'keyword_value' => 'Post',
				],
				[
					'screenId' => '24',
					'keyword_id' => 344,
					'keyword_name' => 'edtCmt',
					'keyword_value' => 'Edit Comment',
				],
				[
					'screenId' => '24',
					'keyword_id' => 345,
					'keyword_name' => 'edtRpl',
					'keyword_value' => 'Edit Reply',
				],
				[
					'screenId' => '24',
					'keyword_id' => 346,
					'keyword_name' => 'dltRpl',
					'keyword_value' => 'Delete Reply',
				],
				[
					'screenId' => '24',
					'keyword_id' => 347,
					'keyword_name' => 'dltCmt',
					'keyword_value' => 'Delete Comment',
				],
				[
					'screenId' => '24',
					'keyword_id' => 348,
					'keyword_name' => 'share',
					'keyword_value' => 'Share',
				],
				[
					'screenId' => '24',
					'keyword_id' => 349,
					'keyword_name' => 'posted',
					'keyword_value' => 'Posted',
				],
				[
					'screenId' => '24',
					'keyword_id' => 350,
					'keyword_name' => 'lblCmt',
					'keyword_value' => 'Comment',
				],
				[
					'screenId' => '24',
					'keyword_id' => 351,
					'keyword_name' => 'lblLike',
					'keyword_value' => 'Like',
				],
				[
					'screenId' => '24',
					'keyword_id' => 352,
					'keyword_name' => 'lblLikes',
					'keyword_value' => 'Likes',
				],
				[
					'screenId' => '24',
					'keyword_id' => 353,
					'keyword_name' => 'lblUMedia',
					'keyword_value' => 'Upload Media',
				],
				[
					'screenId' => '24',
					'keyword_id' => 356,
					'keyword_name' => 'lblOpen',
					'keyword_value' => 'Open',
				],
				[
					'screenId' => '24',
					'keyword_id' => 357,
					'keyword_name' => 'lblPermissionDescription',
					'keyword_value' => 'Media access permission is required to pick files. Please enable it in settings.',
				],
				[
					'screenId' => '24',
					'keyword_id' => 358,
					'keyword_name' => 'confirmDeleteComment',
					'keyword_value' => 'Are you sure you want to delete your comment?',
				],
				[
					'screenId' => '24',
					'keyword_id' => 359,
					'keyword_name' => 'confirmDeleteCommentReply',
					'keyword_value' => 'Are you sure you want to delete your comment reply?',
				],
				[
					'screenId' => '24',
					'keyword_id' => 360,
					'keyword_name' => 'checkOutPost',
					'keyword_value' => 'Check out our post:',
				],
				[
					'screenId' => '24',
					'keyword_id' => 361,
					'keyword_name' => 'readMore',
					'keyword_value' => 'Read more..',
				],
				[
					'screenId' => '24',
					'keyword_id' => 362,
					'keyword_name' => 'readLess',
					'keyword_value' => 'Read less..',
				],
				[
					'screenId' => '24',
					'keyword_id' => 394,
					'keyword_name' => 'lblPosts',
					'keyword_value' => 'Posts',
				],
			],
		],
	];

    foreach ($screen_data as $screen) {
      $screen_record = Screen::where('screenID', $screen['screenID'])->first();

      if ($screen_record == null) {
        $screen_record = Screen::create([
          'screenId'   => $screen['screenID'],
          'screenName' => $screen['ScreenName']
        ]);
      }

      if (isset($screen['keyword_data']) && count($screen['keyword_data']) > 0) {
        foreach ($screen['keyword_data'] as $keyword_data) {
          $keyword_record = DefaultKeyword::where('keyword_id', $keyword_data['keyword_id'])->first();

          if ($keyword_record == null) {
            $keyword_record = DefaultKeyword::create([
              'screen_id' => $screen_record['screenId'],
              'keyword_id' => $keyword_data['keyword_id'],
              'keyword_name' => $keyword_data['keyword_name'],
              'keyword_value' => $keyword_data['keyword_value']
            ]);
          }
        }
      }
    }
  }
}
